from methods.weight_methods_vargrad import (
    METHODS,
    WeightMethods,
    WeightMethod,
    MGDA,
    STL,
    LinearScalarization,
    NashMTL,
    PCGrad,
    Uncertainty,
    CAGrad,
    FairGrad,
    FairGradOriginal,
    FairGradOriginalComposable,
    Vargrad,
)
